Added scripts to test various applications
git-svn-id: file:///jac_sw/svnroot/scicom/trunk/omp/java/qt@1831 64693ad5-8cdc-4012-857f-4cd9bf50b8c8

diff --git a/bin/qt b/bin/qt
--- a/bin/qt
+++ b/bin/qt
@@ -1,35 +1,55 @@
 #!/bin/csh -f 
-######################################################################################### 
-# This file has been automatically generated by "gmake" using the setting in            # 
-# ../conf/make.conf. Modifications can be lost after a new make. 
-# And the format of this script is not really meant to support manual editing.          # 
-######################################################################################### 
- 
+
 set JAVA = /local/java/jdk/bin/java
 
-if (! ${?IMP_SCRATCH} && (${HOST} == "lokahi")) then
-    setenv IMP_SCRATCH /tmp/${USER}
-    echo "IMP_SCRATCH set to /tmp/${USER}"
-endif
- 
-set CFG_DIRS     = /home/mrippa/netroot/install/omp/QT/config/ot/cfg
-set conf        = /home/mrippa/netroot/install/omp/QT/config/qt.conf
-set widgetFile   = /home/mrippa/netroot/install/omp/QT/config/qtUkirtWidget.conf
+set baseOTConfigDir	= /jac_sw/orac3/OT/install/cfg
+set qtConfig	        = /jac_sw/omp/QT/config/qt.conf
+
+set usage		= "Usage: $0 <telescope> [-h] [-options] \n\nwhere telescope is:\n\tukirt\t\tspecifies the UKIRT widget set\n\tjcmt\t\tspecifies the jcmt widget set\n\nand options include:\n\t-jac\t\tspecifies JAC global configs instead of local user configs\n\t-config file\tspecies the absolute path to the \042file\042 used for this session\n\n\n"
+
+set classic = ""
+set xdebug = ""
+set xnoagent = ""
+set xrunjdwptrans = ""
+set xbootclasspath = ""
+
  
 while ($#argv != 0)
    switch ($argv[1])
+      case -h:
+        printf "${usage}" 
+        exit 
+      case -jdebug:
+        set xdebug = "-Xdebug"
+        set xnoagent = "-Xnoagent"
+        set xrunjdwptrans = "-Xrunjdwp:transport=dt_socket,address=2112,server=n,suspend=y"
+        set xbootclasspath = "-Xbootclasspath:/local/java/jdk/jre/lib/rt.jar:/local/java/jdk/lib/tools.jar"
+	echo QT Will be controled by JDEBUG!
+        shift
+        breaksw
       case -jac:
-        set conf = /home/mrippa/netroot/install/omp/QT/configs/qtSystem.conf
+        set qtConfig = /jac_sw/omp/QT/configs/qtSystem.conf
         echo Global configs to be used
         shift
         breaksw
-      case -ukirt:
-       set widgetFile   = /home/mrippa/netroot/install/omp/QT/config/qtUkirtWidget.conf
+      case -config
+        shift
+	set qtConfig = $argv[1]
+        breaksw
+      case -debug
+	set debug = true
+	echo debug on
+        shift
+        breaksw
+      case ukirt:
+        set widgetFile   = /jac_sw/omp/QT/config/qtUkirtWidget.conf
+	set instConfigDir = ${baseOTConfigDir}/ukirt
         echo Telescope set to use ukirt widget set
         shift
         breaksw
-      case -jcmt:
-       set widgetFile   = /home/mrippa/netroot/install/omp/QT/config/qtJcmtWidget.conf
+      case jcmt:
+        set widgetFile   = /jac_sw/omp/QT/config/qtJcmtWidget.conf
+	set instConfigDir = ${baseOTConfigDir}/jcmt
         echo Telescope set to use jcmt widget set
         shift
         breaksw
@@ -40,8 +60,18 @@ while ($#argv != 0)
    endsw
 end
 
-set CLASSPATH = /home/mrippa/netroot/install/omp/QT/lib/qt.jar:/home/mrippa/local/cc/lib/xerces.jar:/home/mrippa/netroot/install/omp/QT/lib/mail.jar:/home/mrippa/netroot/install/omp/QT/lib/activation.jar:/home/mrippa/netroot/install/omp/QT/lib/soap.jar:/home/mrippa/netroot/src/orac3/OT/install/classes:/home/mrippa/netroot/src/orac3/GEMINI/install/classes:/home/mrippa/netroot/src/orac3/OM/install/classes:/home/mrippa/netroot/src/orac3/ORAC/install/classes:/home/mrippa/netroot/src/orac3/ODB/install/classes:/home/mrippa/netroot/install/omp/QT/lib/jsky.jar:/home/mrippa/netroot/install/omp/QT/lib/diva.jar:/home/mrippa/netroot/install/omp/QT/lib/junit.jar
+if !($?widgetFile) then
+    printf "${usage}"
+    exit
+endif
+ 
+if (! ${?IMP_SCRATCH} && (${HOST} == "lokahi")) then
+    setenv IMP_SCRATCH /tmp
+    echo "IMP_SCRATCH set to /tmp"
+endif
 
-set CFG_TELESCOPE_DIR = ${CFG_DIRS}/ukirt
+#cleanup
 
-${JAVA} -DqtConfig=${conf} -DwidgetFile=${widgetFile} -DOMP -DSERVER=ATC -Dot.cfgdir=${CFG_TELESCOPE_DIR}/ -Dot.resource.cfgdir=./ -cp ${CLASSPATH}:${CFG_TELESCOPE_DIR} edu.jach.qt.app.Main &
+set CLASSPATH = /jac_sw/omp/QT/lib/qt.jar:/home/mrippa/local/cc/lib/xerces.jar:/jac_sw/omp/QT/lib/mail.jar:/jac_sw/omp/QT/lib/activation.jar:/jac_sw/omp/QT/lib/soap.jar:/home/mrippa/netroot/src/orac3/OT/install/classes:/home/mrippa/netroot/src/orac3/GEMINI/install/classes:/home/mrippa/netroot/src/orac3/OM/install/classes:/home/mrippa/netroot/src/orac3/ORAC/install/classes:/home/mrippa/netroot/src/orac3/ODB/install/classes:/jac_sw/omp/QT/lib/jsky.jar:/jac_sw/omp/QT/lib/diva.jar:/jac_sw/omp/QT/lib/junit.jar:/jac_sw/omp/QT/icons
+
+${JAVA} ${classic} ${xdebug} ${xnoagent} ${xrunjdwptrans} ${xbootclasspath} -Ddebug=${debug} -DqtConfig=${qtConfig} -Dot.cfgdir=${instConfigDir}/ -DwidgetFile=${widgetFile} -DOMP -cp ${CLASSPATH} edu.jach.qt.app.Main &
